### ISSUE TITLE
WebSockets support

### ISSUE THREAD

**Issue by fr0gs** [mu-semtech/mu-dispatcher#1]
Hello, 

When I try to make a call using websockets from an Ember.js application to a python web server through the dispatcher, I consistently get this error:

```
VM12332:161 WebSocket connection to 'ws://localhost:88/push-service' failed: One or more reserved bits are on: reserved1 = 0, reserved2 = 1, reserved3 = 1
```

When plugging directly the frontend and the backend it works. Does the dispatcher properly proxies websockets calls?

**Comment by madnificent** [comment]
Hi Esteban,

Possibly not.  Part of what @cecton and you are investigating is whether there is a solution that the dispatcher supports and/or what extension would be needed in the dispatcher.  You can try with only the identifier or the dispatcher in between, but that shouldn't make much difference.  It may be that WebSockets are the way to go, but keep an open mind towards technologies.

**Comment by fr0gs** [comment]
Hello @madnificent,

WebSockets seem to work nicely, we are also thinking of alternate options if adding Dispatcher's support for them is too cumbersome.

Thank you!

**Comment by fr0gs** [comment]
Hello, by nicely I mean that it seems to be a good match to solve the push/polling issue, but the dispatcher still does not have support. Potential solutions would be:
- Adding WS support on the dispatcher
- Replacing the dispatcher with another nginx server to do the url rewrital (has support for WS but needs some config)
- Replacing the dispatcher with [https://caddyserver.com/docs/proxy](https://caddyserver.com/docs/proxy). It has default support for WS & the config seems very easy. But again, we'll need to dig into that.

**Comment by madnificent** [comment]
What needs to be done for the first option?

**Comment by fr0gs** [comment]
Right now you can see the traffic representing the initial WS handshake flowing properly through the dispatcher, as it is plain http, but connection is closed by the dispatcher afterwards since it does not understand that that connection must stay alive because traffic will now be over TCP in frames.

The dispatcher could detect the WS call and open two websockets: (frontend, dispatcher) and (dispatcher, backend), and pipe the traffic in between. There may be a library for that in elixir that I don't know.

**Comment by madnificent** [comment]
We will put it on the agenda of the next core team meeting as the hoped content did not arrive from this task.  Thank you for your effort :-)
